import { Inter } from "next/font/google";
import "../styles/main.scss";
import ThemeProvider from "@/context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "bekidink Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ThemeProvider>
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
